import test from 'node:test';
import assert from 'node:assert/strict';
import { generateKeyPair, exportJWK } from 'jose';
import { randomUUID } from 'node:crypto';
import { authenticate, sign, parseMime, mimeMessage, Rejection, validateResult, LIMITS } from '../dist/protocol.js';
import { policyDecision } from '../dist/policy.js';
const pair=await generateKeyPair('ES256',{extractable:true});
const privateKey=await exportJWK(pair.privateKey),publicKey=await exportJWK(pair.publicKey);
const now=Math.floor(Date.now()/1000);
const grant={sender:'fictional-agent',kid:'fictional-key',publicKey,projects:['fictional-project'],actions:['capabilities.get','task.submit','task.status'],replyTo:'test@a2aviary.io',expiresAt:now+3600,research:true};
const request=(changes={})=>({version:'1.0',messageId:randomUUID(),correlationId:randomUUID(),sender:grant.sender,projectId:'fictional-project',action:'task.submit',issuedAt:now,expiresAt:now+300,nonce:randomUUID(),replyTo:grant.replyTo,payload:{brief:'A fictional community garden website.'},...changes});
const verify=async(r,g=grant)=>authenticate(await sign(r,privateKey,grant.kid),async()=>g,now);
test('authenticates real ES256 signed bytes and round-trips MIME',async()=>{const r=request();const jws=await sign(r,privateKey,grant.kid);const mime=mimeMessage('test@a2aviary.io','agent@a2aviary.io',jws,r.messageId,r.correlationId);const parsed=await parseMime(mime);assert.equal(parsed.jws,jws);assert.deepEqual((await verify(r)).request,r);});
test('tampering cannot authorize a payload',async()=>{const jws=await sign(request(),privateKey,grant.kid);const parts=jws.split('.');parts[1]=Buffer.from(JSON.stringify(request({projectId:'other'}))).toString('base64url');await assert.rejects(()=>authenticate(parts.join('.'),async()=>grant,now),e=>e.code==='signature_invalid');});
for(const [label,changes,code]of [['cross-project',{projectId:'other'},'scope_denied'],['unauthorized action',{action:'deployment.create'},'schema_invalid'],['expired',{expiresAt:now-1},'expired'],['future',{issuedAt:now+100,expiresAt:now+300},'expired'],['reply substitution',{replyTo:'unverified@example.com'},'reply_denied'],['schema extra field',{authority:'admin'},'schema_invalid'],['invalid brief',{payload:{brief:42}},'payload_invalid']])test(label,async()=>{await assert.rejects(()=>verify(request(changes)),e=>e.code===code);});
test('revoked and unknown keys cannot execute',async()=>{await assert.rejects(()=>verify(request(),{...grant,revoked:true}),e=>e.code==='identity_invalid');await assert.rejects(()=>verify(request(),null),e=>e.code==='identity_invalid');});
test('research is separately authorized',async()=>{await assert.rejects(()=>verify(request({payload:{brief:'Fictional',research:true}}),{...grant,research:false}),e=>e.code==='research_denied');});
test('raw size and header injection are rejected',async()=>{await assert.rejects(()=>parseMime(Buffer.alloc(LIMITS.rawBytes+1)),e=>e.code==='raw_too_large');assert.throws(()=>mimeMessage('bad\r\nBcc: victim@example.com','test@a2aviary.io','signed','message','correlation'),e=>e.code==='header_invalid');});
test('result schema rejects invented fields and malformed references',()=>{const r={goals:[],audience:'Fictional gardeners',pages:[],missingInputs:[],assumptions:[],acceptanceCriteria:[],references:[]};assert.equal(validateResult(r),true);assert.equal(validateResult({...r,credentials:'x'}),false);assert.equal(validateResult({...r,references:[{title:'x',url:'file:///secret'}]}),false);});
test('sensitive paths and rename origins require current-head owner approval',()=>{const files=[{filename:'docs/note.md',previous_filename:'infra/policy.ts'}];assert.equal(policyDecision(files,[],'head').allowed,false);assert.equal(policyDecision(files,[{user:{login:'a2aviary-operator'},state:'APPROVED',commit_id:'head'}],'head').allowed,false);assert.equal(policyDecision(files,[{user:{login:'carlos-olivera'},state:'APPROVED',commit_id:'old'}],'head').allowed,false);assert.equal(policyDecision(files,[{user:{login:'carlos-olivera'},state:'APPROVED',commit_id:'head'}],'head').allowed,true);assert.equal(policyDecision([{filename:'website/src/styles.css'}],[],'head').allowed,true);});

test('platform auth source and rename origins require owner approval at the current head',()=>{for(const files of [[{filename:'apps/platform/src/auth.ts'}],[{filename:'.dockerignore'}],[{filename:'docs/fictional.md',previous_filename:'apps/platform/src/store.ts'}]]){assert.equal(policyDecision(files,[],'head').allowed,false);assert.equal(policyDecision(files,[{user:{login:'carlos-olivera'},state:'APPROVED',commit_id:'old'}],'head').allowed,false);assert.equal(policyDecision(files,[{user:{login:'carlos-olivera'},state:'APPROVED',commit_id:'head'}],'head').allowed,true);}});

test('generator packages and renamed generator code require current-head owner approval',()=>{for(const files of [[{filename:'packages/generator/src/deploy.ts'}],[{filename:'docs/fictional.md',previous_filename:'packages/generator/src/render.ts'}]]){assert.equal(policyDecision(files,[],'head').allowed,false);assert.equal(policyDecision(files,[{user:{login:'carlos-olivera'},state:'APPROVED',commit_id:'old'}],'head').allowed,false);assert.equal(policyDecision(files,[{user:{login:'carlos-olivera'},state:'APPROVED',commit_id:'head'}],'head').allowed,true);}});
