import { policyDecision } from '../dist/policy.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import { publicQuery, observedUsageExceeded } from '../dist/runtime.js';
import {generateKeyPair,exportJWK,compactVerify,importJWK} from 'jose';
import {authenticate,sign,parseMime,mimeMessage,LIMITS} from '../dist/protocol.js';
import {readFile} from 'node:fs/promises';
const pair=await generateKeyPair('ES256',{extractable:true}),key=await exportJWK(pair.privateKey),pub=await exportJWK(pair.publicKey),at=Math.floor(Date.now()/1000);
const grant={kid:'fictional',publicKey:pub,sender:'fictional',projects:['fictional'],actions:['capabilities.get'],replyTo:'agent@example.com',expiresAt:at+1000};
const req={version:'1.0',messageId:'fictional-message-0001',correlationId:'fictional',sender:'fictional',projectId:'fictional',action:'capabilities.get',issuedAt:at,expiresAt:at+100,nonce:'fictional-nonce-0001',replyTo:grant.replyTo,payload:{}};
test('research accepts only explicit public topics and rejects secret-bearing topics',()=>{assert.equal(publicQuery('community garden accessibility',['community garden accessibility']),'community garden accessibility');for(const q of ['unapproved topic','owner@example.com','secret customer document','password data','private attachment','line\nbreak'])assert.throws(()=>publicQuery(q,[q==='unapproved topic'?'approved topic':q]),e=>e.code==='research_query_denied');});
test('unsupported algorithm and oversized signed payload reject before authority',async()=>{const jws=await sign(req,key,'fictional');const parts=jws.split('.');parts[0]=Buffer.from(JSON.stringify({alg:'HS256',kid:'fictional'})).toString('base64url');await assert.rejects(()=>authenticate(parts.join('.'),async()=>grant,at),e=>e.code==='key_invalid');const large=await sign({...req,payload:{text:'a'.repeat(LIMITS.payloadBytes)}},key,'fictional');await assert.rejects(()=>authenticate(large,async()=>grant,at),e=>e.code==='payload_too_large');});
test('unsupported binary MIME attachment rejects',async()=>{const raw=mimeMessage('agent@example.com','agent@a2aviary.io',await sign(req,key,'fictional'),req.messageId,req.correlationId);const text=raw.toString(),boundary=/boundary="([^"]+)"/.exec(text)[1];const modified=text.replace(`--${boundary}--`,`--${boundary}\r\nContent-Type: application/octet-stream\r\nContent-Disposition: attachment; filename="payload.zip"\r\n\r\narchive\r\n--${boundary}--`);await assert.rejects(()=>parseMime(Buffer.from(modified)),e=>e.code==='attachment_invalid');});
test('offline fictional example has a valid ES256 signature',async()=>{const pub=JSON.parse(await readFile('../contracts/examples/public-key.json','utf8'));const eml=await parseMime(await readFile('../contracts/examples/request.eml'));const verified=await compactVerify(eml.jws,await importJWK(pub.jwk,'ES256'),{algorithms:['ES256']});assert.equal(JSON.parse(Buffer.from(verified.payload).toString()).projectId,'fictional-garden');});
test('attachment references bind every byte exactly once',async()=>{const {bindAttachments,hash}=await import('../dist/protocol.js');const a={filename:'a.txt',content:Buffer.from('fictional A')},b={filename:'b.txt',content:Buffer.from('fictional B')};const ref={filename:a.filename,sha256:hash(a.content)};assert.doesNotThrow(()=>bindAttachments([ref],[a]));assert.throws(()=>bindAttachments([ref],[{...a,content:Buffer.from('changed')}]),e=>e.code==='attachment_binding');assert.throws(()=>bindAttachments([ref,ref],[a,b]),e=>e.code==='attachment_binding');assert.throws(()=>bindAttachments([ref],[a,b]),e=>e.code==='attachment_binding');});
test('owner and partner limits can reduce allowances without expanding authority',async()=>{const {effectiveLimits,capabilities}=await import('../dist/protocol.js');assert.equal(effectiveLimits({limits:{toolCalls:1}}).toolCalls,1);assert.throws(()=>effectiveLimits({limits:{toolCalls:1000}}));assert.throws(()=>effectiveLimits({limits:{monthMicros:1}}));assert.deepEqual(capabilities({...grant,actions:['capabilities.get']}).taskTypes,[]);const limited={...grant,limits:{payloadBytes:10}};const jws=await sign(req,key,grant.kid);await assert.rejects(()=>authenticate(jws,async()=>limited,at),e=>e.code==='payload_too_large');});

test('bundled licenses and architecture authority cannot bypass sensitive-path approval',()=>{for(const filename of ['website/public/licenses/inter-OFL.txt','docs/decisions/005-github-identity-and-policy.md','services/THIRD_PARTY.md'])assert.equal(policyDecision([{filename}],[],'head').allowed,false);});

test('research inference contributes to the task token and dollar allowances',()=>{assert.equal(observedUsageExceeded({input_tokens:31000,output_tokens:1000},{toolInputTokens:1001}),true);assert.equal(observedUsageExceeded({input_tokens:1000,output_tokens:7500},{toolOutputTokens:501}),true);assert.equal(observedUsageExceeded({input_tokens:1000,output_tokens:1000},{toolInputTokens:1000,toolOutputTokens:1000,toolCostMicros:10000}),false);assert.equal(observedUsageExceeded(null,{toolCostMicros:1000001}),true);});
